### PR TITLE
Upgrades for PureScript 0.12

### PR DESCRIPTION
**Pull request by paluh**

### CODE REVIEW

**Comment by paluh** [comment]
There are still minor issues:

* bower.json contains this dependency: `"purescript-node-os": "thimoteus/purescript-node-os#master"`

* There are 8 warnings related to import format in `src/Snai.purs`

  Compiler suggests that we should use explicit form of imports for example:

   instead of this:

   ``` purescript
   import Snail.Types as Types
   ```

   use this:

   ``` purescript
   import Snail.Types (class Address, FILE, FOLDER, File, Folder, Script, Snail, file, folder, getAddress, runFile, runFolder) as Types
   ```
    @Thimoteus  Should I use this format of imports?

**Comment by Thimoteus** [comment]
Hmm, that's a little surprising, since that's the only module being imported as `Types`. Are qualified implicit exports a warning now under 0.12.1?

**Comment by paluh** [comment]
No, no. It is strictly related to reexports which are done in this module. The whole example message is like this:

``` shell
Module Snail.Types was imported as Types with unspecified imports.                                                                                                
As this module is being re-exported, consider using the explicit form:

  import Snail.Types (class Address, FILE, FOLDER, File, Folder, Script, Snail, file, folder, getAddress, runFile, runFolder) as Types

See https://github.com/purescript/documentation/blob/master/errors/ImplicitQualifiedImportReExport.md for more information, or to contribute content related to this warning.
```

We have 8 such warnings as we are doing multiple reexports there.

**Comment by Thimoteus** [comment]
Interesting. Since it's giving a warning regardless, maybe it's better to use an explicit import list and just use the same module name for them all, like `Exports`.

**Comment by paluh** [comment]
I'm not sure if we are gaining anything by flattening namespace to `Exports` as this module name won't be exposed to the outside user. Reexported symbols can be accessed in the same manner as any local symbols defined in given module. For example:

``` purescript
import Snail (echo)
```

Do you want to flatten this namespace anyway?

P.S. I've added explicit lists of imports - no more compilation warnings.

**Comment by Thimoteus** [comment]
It's just to shorten the reexport list, so there's only one line of module reexports.

**Comment by paluh** [comment]
@Thimoteus Can I leave it as it is? ;-)

**Comment by Thimoteus** [comment]
Sure. Does that mean it's ready?

**Comment by paluh** [comment]
Yeah.

**Comment by paluh** [comment]
Oh sorry,

The last thing - `Snail` and `Script` are now really naive aliases:

``` purescript
type Snail = Aff
type Script = Effect
```

Should we leave them?

**Comment by Thimoteus** [comment]
Hmm, well it'll be a breaking change anyway, so maybe it's best to get rid of them.

**Comment by paluh** [comment]
Yeah, I can drop them from the lib now. On the other hand...
I'm for example finding `MonadError` instance of `Aff` somewhat disturbing as I'm not able to `lmap` over it... I'm not sure if this library is the best place to provide `newtype` versions of these aliases but from my perspective they could be really useful. Maybe this is a topic for separate discussion ;-)

**Comment by paluh** [comment]
Done.

**Comment by Thimoteus** [comment]
Sweet, thanks!

**Pull request merged**
